name: Deploy test world

on:
  push:
    branches:
      - main

env:
  DCL_PRIVATE_KEY: ${{ secrets.DCL_PRIVATE_KEY }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install decentraland
        run: npm i -g decentraland@latest
      - name: install dependencies
        run: npm i
      - name: build
        run: npm run build:ci
      - name: deploy
        run: npm run deploy:testing